### ISSUE TITLE
Recommend adding case-sensitive error

### ISSUE THREAD

**Issue by newphew92** [reasonml/BetterErrors#25]
I recommend adding a new error message for this particular union type for when you forget to put a cap on the first letter.
![screen shot 2016-02-25 at 9 49 46 pm](https://cloud.githubusercontent.com/assets/5588583/13341794/bcfdf4e2-dc09-11e5-9f94-b6d61f00a484.png)

**Comment by chenglou** [comment]
Should be a quick regex to check the previous few chars for `|`. Won't catch `type bla = a | B` but that should be good enough.

**Comment by chenglou** [comment]
Wait no, pattern matching uses the bar too. So this is too unreliable. Maybe we should check for `of` (otherwise just bail...).

Oooor maybe we should really just have better syntax error messages from the compiler.

**Comment by chenglou** [comment]
cc @jordwalke on this one because eeeverybody trips on capitalization problems (cough)

**Comment by jordwalke** [comment]
This is something that can be fixed by Menhir error databases I believe.

**Comment by bsansouci** [comment]
The inverse problem happened to me where I wrote my types with upper cases and it syntax-errorer.

**Comment by chenglou** [comment]
Well this sure took longer than it should have. Fixed by https://github.com/facebook/reason/pull/937
