### ISSUE TITLE
Failed to install ocamlBetterErrors from npm

### ISSUE THREAD

**Issue by nikgraf** [reasonml/BetterErrors#82]
```
npm install -g ocamlBetterErrors

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @opam-alpha/ppx_tools_versioned@= 5.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'reason-parser-actual'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2017-06-20T18_26_20_867Z-debug.log
```

**Comment by jordwalke** [comment]
Were you aware that `reason-cli` distributes `bettererrors`? `reason-cli` removes most of the build and package complexity for the set of dev tools that we want to make easily installable. Will it work for you?

**Comment by nikgraf** [comment]
Totally wasn't. Just noticed I didn't have reason-cli after switching to a new node version. Yesterday I only noticed I'm missing `berrors` and then tried to resolve the issue by going to this repo and running the recommended command.

Would you accept a PR in the README hinting that it ships with reason-cli and this should be the recommend way to install?

**Comment by jordwalke** [comment]
Absolutely would accept such a PR.

**Comment by nikgraf** [comment]
https://github.com/reasonml/BetterErrors/pull/83
